# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settings_form(object):
    def setupUi(self, settings_form):
        settings_form.setObjectName("settings_form")
        settings_form.resize(700, 500)
        settings_form.setMinimumSize(QtCore.QSize(700, 500))
        settings_form.setMaximumSize(QtCore.QSize(700, 500))
        self.color_F = QtWidgets.QFrame(settings_form)
        self.color_F.setGeometry(QtCore.QRect(50, 340, 600, 50))
        self.color_F.setMinimumSize(QtCore.QSize(600, 40))
        self.color_F.setMaximumSize(QtCore.QSize(16777215, 60))
        self.color_F.setObjectName("color_F")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.color_F)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.color_L = QtWidgets.QLabel(self.color_F)
        self.color_L.setMinimumSize(QtCore.QSize(150, 30))
        self.color_L.setObjectName("color_L")
        self.horizontalLayout.addWidget(self.color_L)
        self.R_SB = QtWidgets.QSpinBox(self.color_F)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.R_SB.sizePolicy().hasHeightForWidth())
        self.R_SB.setSizePolicy(sizePolicy)
        self.R_SB.setMinimumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.R_SB.setFont(font)
        self.R_SB.setMaximum(255)
        self.R_SB.setObjectName("R_SB")
        self.horizontalLayout.addWidget(self.R_SB)
        self.G_SB = QtWidgets.QSpinBox(self.color_F)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.G_SB.sizePolicy().hasHeightForWidth())
        self.G_SB.setSizePolicy(sizePolicy)
        self.G_SB.setMinimumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.G_SB.setFont(font)
        self.G_SB.setMaximum(255)
        self.G_SB.setProperty("value", 255)
        self.G_SB.setObjectName("G_SB")
        self.horizontalLayout.addWidget(self.G_SB)
        self.B_SB = QtWidgets.QSpinBox(self.color_F)
        self.B_SB.setMinimumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.B_SB.setFont(font)
        self.B_SB.setMaximum(255)
        self.B_SB.setObjectName("B_SB")
        self.horizontalLayout.addWidget(self.B_SB)
        self.size_F = QtWidgets.QFrame(settings_form)
        self.size_F.setGeometry(QtCore.QRect(125, 390, 450, 50))
        self.size_F.setMinimumSize(QtCore.QSize(0, 40))
        self.size_F.setObjectName("size_F")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.size_F)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.size_L = QtWidgets.QLabel(self.size_F)
        self.size_L.setMinimumSize(QtCore.QSize(120, 30))
        self.size_L.setMaximumSize(QtCore.QSize(120, 120))
        self.size_L.setObjectName("size_L")
        self.horizontalLayout_2.addWidget(self.size_L)
        self.W_SB = QtWidgets.QSpinBox(self.size_F)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.W_SB.sizePolicy().hasHeightForWidth())
        self.W_SB.setSizePolicy(sizePolicy)
        self.W_SB.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.W_SB.setFont(font)
        self.W_SB.setMinimum(120)
        self.W_SB.setMaximum(800)
        self.W_SB.setProperty("value", 640)
        self.W_SB.setObjectName("W_SB")
        self.horizontalLayout_2.addWidget(self.W_SB)
        self.H_SB = QtWidgets.QSpinBox(self.size_F)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.H_SB.sizePolicy().hasHeightForWidth())
        self.H_SB.setSizePolicy(sizePolicy)
        self.H_SB.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.H_SB.setFont(font)
        self.H_SB.setMinimum(80)
        self.H_SB.setMaximum(600)
        self.H_SB.setProperty("value", 480)
        self.H_SB.setObjectName("H_SB")
        self.horizontalLayout_2.addWidget(self.H_SB)
        self.back_BTN = QtWidgets.QPushButton(settings_form)
        self.back_BTN.setGeometry(QtCore.QRect(250, 450, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.back_BTN.setFont(font)
        self.back_BTN.setObjectName("back_BTN")

        self.retranslateUi(settings_form)
        QtCore.QMetaObject.connectSlotsByName(settings_form)

    def retranslateUi(self, settings_form):
        _translate = QtCore.QCoreApplication.translate
        settings_form.setWindowTitle(_translate("settings_form", "Expression Recognizer"))
        self.color_L.setText(_translate("settings_form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">COLOR(RGB):</span></p></body></html>"))
        self.size_L.setText(_translate("settings_form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">SIZE:</span></p></body></html>"))
        self.back_BTN.setText(_translate("settings_form", "Back"))

